defaultBaseImage: gcr.io/k8s-staging-build-image/debian-base:bookworm-v1.0.6
# https://pkg.go.dev/cmd/link
# -s: omit symbol/debug info
# -w: omit DWARF symbol table
# -X importpath.name=value: sets name to value
builds:
- ldflags:
  - -s -w
