steps:
# Push the images
- name: "mirror.gcr.io/library/golang:1.24.4-bookworm"
  id: etcd-manager-slim-image
  entrypoint: make
  env:
  - PULL_BASE_REF=$_PULL_BASE_REF
  # We don't pass version; we want to use our own version tagging from git
  #- VERSION=$_GIT_TAG
  - DOCKER_REGISTRY=$_DOCKER_REGISTRY
  - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
  args:
  - push-etcd-manager-slim
- name: "mirror.gcr.io/library/golang:1.24.4-bookworm"
  id: etcd-backup-image
  entrypoint: make
  env:
  - PULL_BASE_REF=$_PULL_BASE_REF
  # We don't pass version; we want to use our own version tagging from git
  #- VERSION=$_GIT_TAG
  - DOCKER_REGISTRY=$_DOCKER_REGISTRY
  - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
  args:
  - push-etcd-backup
- name: "mirror.gcr.io/library/golang:1.24.4-bookworm"
  id: etcd-dump-image
  entrypoint: make
  env:
  - PULL_BASE_REF=$_PULL_BASE_REF
  # We don't pass version; we want to use our own version tagging from git
  #- VERSION=$_GIT_TAG
  - DOCKER_REGISTRY=$_DOCKER_REGISTRY
  - DOCKER_IMAGE_PREFIX=$_DOCKER_IMAGE_PREFIX
  args:
  - push-etcd-dump
timeout: 1800s
substitutions:
  _DOCKER_REGISTRY: 'us-central1-docker.pkg.dev'
  _DOCKER_IMAGE_PREFIX: 'k8s-staging-images/etcd-manager/'
  _GIT_TAG: 'dev'
  _PULL_BASE_REF: 'dev'
options:
  machineType: E2_HIGHCPU_8
  substitution_option: ALLOW_LOOSE
