#!/bin/bash

set -ex

# One-time plugin install (requires Go toolchain with $(go env GOPATH)/bin on PATH):
#   go install google.golang.org/protobuf/cmd/protoc-gen-go@latest
#   go install google.golang.org/grpc/cmd/protoc-gen-go-grpc@latest

for f in $(find pkg/ -name '*.proto'); do
  protoc \
    --go_out=. --go_opt=paths=source_relative \
    --go-grpc_out=. --go-grpc_opt=paths=source_relative \
    --go-grpc_opt=require_unimplemented_servers=false \
    "$f"
done

for f in $(find pkg/ -name '*.pb.go'); do
  cat > "$f.tmp" <<'HEADER'
/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
HEADER

  cat "$f" >> "$f.tmp"
  mv "$f.tmp" "$f"
done
