#!/bin/bash
#
# Copyright 2024 The Kubernetes Authors.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#     http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.

set -o errexit
set -o nounset
set -o pipefail

REPO_ROOT="$(git rev-parse --show-toplevel)"
cd "${REPO_ROOT}"

if [[ -z "${IMAGE_PREFIX:-}" ]]; then
    echo "IMAGE_PREFIX is not set"
    exit 1
fi

IMAGE_TAG=${IMAGE_PREFIX}etcd-manager-static:latest

if [[ -z "${BUILD_ARGS:-}" ]]; then
    BUILD_ARGS="--load"
fi

if [[ -z "${BUILD_PLATFORMS:-}" ]]; then
    BUILD_PLATFORMS="local"
fi

echo "Building image ${IMAGE_TAG} for platforms ${BUILD_PLATFORMS} with args ${BUILD_ARGS:-}"

docker buildx build ${BUILD_ARGS} --platform ${BUILD_PLATFORMS} -t ${IMAGE_TAG} -f ./images/etcd-manager-static/Dockerfile .
