/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: pkg/privateapi/cluster.proto

package privateapi

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type PingRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PeerInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingRequest) Reset() {
	*x = PingRequest{}
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingRequest) ProtoMessage() {}

func (x *PingRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingRequest.ProtoReflect.Descriptor instead.
func (*PingRequest) Descriptor() ([]byte, []int) {
	return file_pkg_privateapi_cluster_proto_rawDescGZIP(), []int{0}
}

func (x *PingRequest) GetInfo() *PeerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PingResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Info          *PeerInfo              `protobuf:"bytes,1,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PingResponse) Reset() {
	*x = PingResponse{}
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PingResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PingResponse) ProtoMessage() {}

func (x *PingResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PingResponse.ProtoReflect.Descriptor instead.
func (*PingResponse) Descriptor() ([]byte, []int) {
	return file_pkg_privateapi_cluster_proto_rawDescGZIP(), []int{1}
}

func (x *PingResponse) GetInfo() *PeerInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type PeerInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Endpoints     []string               `protobuf:"bytes,2,rep,name=endpoints,proto3" json:"endpoints,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PeerInfo) Reset() {
	*x = PeerInfo{}
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PeerInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PeerInfo) ProtoMessage() {}

func (x *PeerInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PeerInfo.ProtoReflect.Descriptor instead.
func (*PeerInfo) Descriptor() ([]byte, []int) {
	return file_pkg_privateapi_cluster_proto_rawDescGZIP(), []int{2}
}

func (x *PeerInfo) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *PeerInfo) GetEndpoints() []string {
	if x != nil {
		return x.Endpoints
	}
	return nil
}

type View struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Leader          *PeerInfo              `protobuf:"bytes,1,opt,name=leader,proto3" json:"leader,omitempty"`
	LeadershipToken string                 `protobuf:"bytes,2,opt,name=leadership_token,json=leadershipToken,proto3" json:"leadership_token,omitempty"`
	Healthy         []*PeerInfo            `protobuf:"bytes,3,rep,name=healthy,proto3" json:"healthy,omitempty"` //    repeated PeerInfo unhealthy = 2;
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *View) Reset() {
	*x = View{}
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *View) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*View) ProtoMessage() {}

func (x *View) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use View.ProtoReflect.Descriptor instead.
func (*View) Descriptor() ([]byte, []int) {
	return file_pkg_privateapi_cluster_proto_rawDescGZIP(), []int{3}
}

func (x *View) GetLeader() *PeerInfo {
	if x != nil {
		return x.Leader
	}
	return nil
}

func (x *View) GetLeadershipToken() string {
	if x != nil {
		return x.LeadershipToken
	}
	return ""
}

func (x *View) GetHealthy() []*PeerInfo {
	if x != nil {
		return x.Healthy
	}
	return nil
}

type LeaderNotificationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	View          *View                  `protobuf:"bytes,1,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderNotificationRequest) Reset() {
	*x = LeaderNotificationRequest{}
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderNotificationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderNotificationRequest) ProtoMessage() {}

func (x *LeaderNotificationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderNotificationRequest.ProtoReflect.Descriptor instead.
func (*LeaderNotificationRequest) Descriptor() ([]byte, []int) {
	return file_pkg_privateapi_cluster_proto_rawDescGZIP(), []int{4}
}

func (x *LeaderNotificationRequest) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

type LeaderNotificationResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// True if this node acknowledges the new leader
	Accepted bool `protobuf:"varint,1,opt,name=accepted,proto3" json:"accepted,omitempty"`
	// If the node has a different (bigger) view, it rejects the leadership bid and sends the view
	View          *View `protobuf:"bytes,2,opt,name=view,proto3" json:"view,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LeaderNotificationResponse) Reset() {
	*x = LeaderNotificationResponse{}
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LeaderNotificationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LeaderNotificationResponse) ProtoMessage() {}

func (x *LeaderNotificationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_privateapi_cluster_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LeaderNotificationResponse.ProtoReflect.Descriptor instead.
func (*LeaderNotificationResponse) Descriptor() ([]byte, []int) {
	return file_pkg_privateapi_cluster_proto_rawDescGZIP(), []int{5}
}

func (x *LeaderNotificationResponse) GetAccepted() bool {
	if x != nil {
		return x.Accepted
	}
	return false
}

func (x *LeaderNotificationResponse) GetView() *View {
	if x != nil {
		return x.View
	}
	return nil
}

var File_pkg_privateapi_cluster_proto protoreflect.FileDescriptor

const file_pkg_privateapi_cluster_proto_rawDesc = "" +
	"\n" +
	"\x1cpkg/privateapi/cluster.proto\x12\n" +
	"privateapi\"7\n" +
	"\vPingRequest\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x14.privateapi.PeerInfoR\x04info\"8\n" +
	"\fPingResponse\x12(\n" +
	"\x04info\x18\x01 \x01(\v2\x14.privateapi.PeerInfoR\x04info\"8\n" +
	"\bPeerInfo\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x1c\n" +
	"\tendpoints\x18\x02 \x03(\tR\tendpoints\"\x8f\x01\n" +
	"\x04View\x12,\n" +
	"\x06leader\x18\x01 \x01(\v2\x14.privateapi.PeerInfoR\x06leader\x12)\n" +
	"\x10leadership_token\x18\x02 \x01(\tR\x0fleadershipToken\x12.\n" +
	"\ahealthy\x18\x03 \x03(\v2\x14.privateapi.PeerInfoR\ahealthy\"A\n" +
	"\x19LeaderNotificationRequest\x12$\n" +
	"\x04view\x18\x01 \x01(\v2\x10.privateapi.ViewR\x04view\"^\n" +
	"\x1aLeaderNotificationResponse\x12\x1a\n" +
	"\baccepted\x18\x01 \x01(\bR\baccepted\x12$\n" +
	"\x04view\x18\x02 \x01(\v2\x10.privateapi.ViewR\x04view2\xb0\x01\n" +
	"\x0eClusterService\x129\n" +
	"\x04Ping\x12\x17.privateapi.PingRequest\x1a\x18.privateapi.PingResponse\x12c\n" +
	"\x12LeaderNotification\x12%.privateapi.LeaderNotificationRequest\x1a&.privateapi.LeaderNotificationResponseB)Z'sigs.k8s.io/etcd-manager/pkg/privateapib\x06proto3"

var (
	file_pkg_privateapi_cluster_proto_rawDescOnce sync.Once
	file_pkg_privateapi_cluster_proto_rawDescData []byte
)

func file_pkg_privateapi_cluster_proto_rawDescGZIP() []byte {
	file_pkg_privateapi_cluster_proto_rawDescOnce.Do(func() {
		file_pkg_privateapi_cluster_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_privateapi_cluster_proto_rawDesc), len(file_pkg_privateapi_cluster_proto_rawDesc)))
	})
	return file_pkg_privateapi_cluster_proto_rawDescData
}

var file_pkg_privateapi_cluster_proto_msgTypes = make([]protoimpl.MessageInfo, 6)
var file_pkg_privateapi_cluster_proto_goTypes = []any{
	(*PingRequest)(nil),                // 0: privateapi.PingRequest
	(*PingResponse)(nil),               // 1: privateapi.PingResponse
	(*PeerInfo)(nil),                   // 2: privateapi.PeerInfo
	(*View)(nil),                       // 3: privateapi.View
	(*LeaderNotificationRequest)(nil),  // 4: privateapi.LeaderNotificationRequest
	(*LeaderNotificationResponse)(nil), // 5: privateapi.LeaderNotificationResponse
}
var file_pkg_privateapi_cluster_proto_depIdxs = []int32{
	2, // 0: privateapi.PingRequest.info:type_name -> privateapi.PeerInfo
	2, // 1: privateapi.PingResponse.info:type_name -> privateapi.PeerInfo
	2, // 2: privateapi.View.leader:type_name -> privateapi.PeerInfo
	2, // 3: privateapi.View.healthy:type_name -> privateapi.PeerInfo
	3, // 4: privateapi.LeaderNotificationRequest.view:type_name -> privateapi.View
	3, // 5: privateapi.LeaderNotificationResponse.view:type_name -> privateapi.View
	0, // 6: privateapi.ClusterService.Ping:input_type -> privateapi.PingRequest
	4, // 7: privateapi.ClusterService.LeaderNotification:input_type -> privateapi.LeaderNotificationRequest
	1, // 8: privateapi.ClusterService.Ping:output_type -> privateapi.PingResponse
	5, // 9: privateapi.ClusterService.LeaderNotification:output_type -> privateapi.LeaderNotificationResponse
	8, // [8:10] is the sub-list for method output_type
	6, // [6:8] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_pkg_privateapi_cluster_proto_init() }
func file_pkg_privateapi_cluster_proto_init() {
	if File_pkg_privateapi_cluster_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_privateapi_cluster_proto_rawDesc), len(file_pkg_privateapi_cluster_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   6,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_privateapi_cluster_proto_goTypes,
		DependencyIndexes: file_pkg_privateapi_cluster_proto_depIdxs,
		MessageInfos:      file_pkg_privateapi_cluster_proto_msgTypes,
	}.Build()
	File_pkg_privateapi_cluster_proto = out.File
	file_pkg_privateapi_cluster_proto_goTypes = nil
	file_pkg_privateapi_cluster_proto_depIdxs = nil
}
