/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v5.26.1
// source: pkg/apis/etcd/etcdapi.proto

package etcd

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	EtcdManagerService_GetInfo_FullMethodName         = "/etcd.EtcdManagerService/GetInfo"
	EtcdManagerService_UpdateEndpoints_FullMethodName = "/etcd.EtcdManagerService/UpdateEndpoints"
	EtcdManagerService_JoinCluster_FullMethodName     = "/etcd.EtcdManagerService/JoinCluster"
	EtcdManagerService_Reconfigure_FullMethodName     = "/etcd.EtcdManagerService/Reconfigure"
	EtcdManagerService_DoBackup_FullMethodName        = "/etcd.EtcdManagerService/DoBackup"
	EtcdManagerService_DoRestore_FullMethodName       = "/etcd.EtcdManagerService/DoRestore"
	EtcdManagerService_StopEtcd_FullMethodName        = "/etcd.EtcdManagerService/StopEtcd"
)

// EtcdManagerServiceClient is the client API for EtcdManagerService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type EtcdManagerServiceClient interface {
	// GetInfo gets info about the node
	GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error)
	// UpdateEndpoints is sent to peers so they can update their inter-cluster routing
	UpdateEndpoints(ctx context.Context, in *UpdateEndpointsRequest, opts ...grpc.CallOption) (*UpdateEndpointsResponse, error)
	// JoinCluster requests that the node join an existing cluster
	JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error)
	// Reconfigure changes the configuration of an existing node, primarily for a version upgrade/downgrade
	Reconfigure(ctx context.Context, in *ReconfigureRequest, opts ...grpc.CallOption) (*ReconfigureResponse, error)
	// DoBackup requests that the node backup etcd
	DoBackup(ctx context.Context, in *DoBackupRequest, opts ...grpc.CallOption) (*DoBackupResponse, error)
	// DoRestore requests that the node restores an etcd backup
	DoRestore(ctx context.Context, in *DoRestoreRequest, opts ...grpc.CallOption) (*DoRestoreResponse, error)
	// StopEtcd requests that the node no longer run etcd.
	// Typically the node will already have been removed from the etcd cluster.
	StopEtcd(ctx context.Context, in *StopEtcdRequest, opts ...grpc.CallOption) (*StopEtcdResponse, error)
}

type etcdManagerServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewEtcdManagerServiceClient(cc grpc.ClientConnInterface) EtcdManagerServiceClient {
	return &etcdManagerServiceClient{cc}
}

func (c *etcdManagerServiceClient) GetInfo(ctx context.Context, in *GetInfoRequest, opts ...grpc.CallOption) (*GetInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetInfoResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_GetInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdManagerServiceClient) UpdateEndpoints(ctx context.Context, in *UpdateEndpointsRequest, opts ...grpc.CallOption) (*UpdateEndpointsResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateEndpointsResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_UpdateEndpoints_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdManagerServiceClient) JoinCluster(ctx context.Context, in *JoinClusterRequest, opts ...grpc.CallOption) (*JoinClusterResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(JoinClusterResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_JoinCluster_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdManagerServiceClient) Reconfigure(ctx context.Context, in *ReconfigureRequest, opts ...grpc.CallOption) (*ReconfigureResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReconfigureResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_Reconfigure_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdManagerServiceClient) DoBackup(ctx context.Context, in *DoBackupRequest, opts ...grpc.CallOption) (*DoBackupResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoBackupResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_DoBackup_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdManagerServiceClient) DoRestore(ctx context.Context, in *DoRestoreRequest, opts ...grpc.CallOption) (*DoRestoreResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DoRestoreResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_DoRestore_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *etcdManagerServiceClient) StopEtcd(ctx context.Context, in *StopEtcdRequest, opts ...grpc.CallOption) (*StopEtcdResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StopEtcdResponse)
	err := c.cc.Invoke(ctx, EtcdManagerService_StopEtcd_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// EtcdManagerServiceServer is the server API for EtcdManagerService service.
// All implementations should embed UnimplementedEtcdManagerServiceServer
// for forward compatibility.
type EtcdManagerServiceServer interface {
	// GetInfo gets info about the node
	GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error)
	// UpdateEndpoints is sent to peers so they can update their inter-cluster routing
	UpdateEndpoints(context.Context, *UpdateEndpointsRequest) (*UpdateEndpointsResponse, error)
	// JoinCluster requests that the node join an existing cluster
	JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error)
	// Reconfigure changes the configuration of an existing node, primarily for a version upgrade/downgrade
	Reconfigure(context.Context, *ReconfigureRequest) (*ReconfigureResponse, error)
	// DoBackup requests that the node backup etcd
	DoBackup(context.Context, *DoBackupRequest) (*DoBackupResponse, error)
	// DoRestore requests that the node restores an etcd backup
	DoRestore(context.Context, *DoRestoreRequest) (*DoRestoreResponse, error)
	// StopEtcd requests that the node no longer run etcd.
	// Typically the node will already have been removed from the etcd cluster.
	StopEtcd(context.Context, *StopEtcdRequest) (*StopEtcdResponse, error)
}

// UnimplementedEtcdManagerServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedEtcdManagerServiceServer struct{}

func (UnimplementedEtcdManagerServiceServer) GetInfo(context.Context, *GetInfoRequest) (*GetInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetInfo not implemented")
}
func (UnimplementedEtcdManagerServiceServer) UpdateEndpoints(context.Context, *UpdateEndpointsRequest) (*UpdateEndpointsResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateEndpoints not implemented")
}
func (UnimplementedEtcdManagerServiceServer) JoinCluster(context.Context, *JoinClusterRequest) (*JoinClusterResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method JoinCluster not implemented")
}
func (UnimplementedEtcdManagerServiceServer) Reconfigure(context.Context, *ReconfigureRequest) (*ReconfigureResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Reconfigure not implemented")
}
func (UnimplementedEtcdManagerServiceServer) DoBackup(context.Context, *DoBackupRequest) (*DoBackupResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DoBackup not implemented")
}
func (UnimplementedEtcdManagerServiceServer) DoRestore(context.Context, *DoRestoreRequest) (*DoRestoreResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method DoRestore not implemented")
}
func (UnimplementedEtcdManagerServiceServer) StopEtcd(context.Context, *StopEtcdRequest) (*StopEtcdResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StopEtcd not implemented")
}
func (UnimplementedEtcdManagerServiceServer) testEmbeddedByValue() {}

// UnsafeEtcdManagerServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to EtcdManagerServiceServer will
// result in compilation errors.
type UnsafeEtcdManagerServiceServer interface {
	mustEmbedUnimplementedEtcdManagerServiceServer()
}

func RegisterEtcdManagerServiceServer(s grpc.ServiceRegistrar, srv EtcdManagerServiceServer) {
	// If the following call panics, it indicates UnimplementedEtcdManagerServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&EtcdManagerService_ServiceDesc, srv)
}

func _EtcdManagerService_GetInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).GetInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_GetInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).GetInfo(ctx, req.(*GetInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdManagerService_UpdateEndpoints_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateEndpointsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).UpdateEndpoints(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_UpdateEndpoints_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).UpdateEndpoints(ctx, req.(*UpdateEndpointsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdManagerService_JoinCluster_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(JoinClusterRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).JoinCluster(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_JoinCluster_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).JoinCluster(ctx, req.(*JoinClusterRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdManagerService_Reconfigure_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReconfigureRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).Reconfigure(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_Reconfigure_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).Reconfigure(ctx, req.(*ReconfigureRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdManagerService_DoBackup_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoBackupRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).DoBackup(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_DoBackup_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).DoBackup(ctx, req.(*DoBackupRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdManagerService_DoRestore_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DoRestoreRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).DoRestore(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_DoRestore_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).DoRestore(ctx, req.(*DoRestoreRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _EtcdManagerService_StopEtcd_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StopEtcdRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(EtcdManagerServiceServer).StopEtcd(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: EtcdManagerService_StopEtcd_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(EtcdManagerServiceServer).StopEtcd(ctx, req.(*StopEtcdRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// EtcdManagerService_ServiceDesc is the grpc.ServiceDesc for EtcdManagerService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var EtcdManagerService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "etcd.EtcdManagerService",
	HandlerType: (*EtcdManagerServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetInfo",
			Handler:    _EtcdManagerService_GetInfo_Handler,
		},
		{
			MethodName: "UpdateEndpoints",
			Handler:    _EtcdManagerService_UpdateEndpoints_Handler,
		},
		{
			MethodName: "JoinCluster",
			Handler:    _EtcdManagerService_JoinCluster_Handler,
		},
		{
			MethodName: "Reconfigure",
			Handler:    _EtcdManagerService_Reconfigure_Handler,
		},
		{
			MethodName: "DoBackup",
			Handler:    _EtcdManagerService_DoBackup_Handler,
		},
		{
			MethodName: "DoRestore",
			Handler:    _EtcdManagerService_DoRestore_Handler,
		},
		{
			MethodName: "StopEtcd",
			Handler:    _EtcdManagerService_StopEtcd_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "pkg/apis/etcd/etcdapi.proto",
}
