/*
Copyright 2020 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/
// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v5.26.1
// source: pkg/apis/etcd/etcdapi.proto

package etcd

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Phase int32

const (
	Phase_PHASE_UNKNOWN         Phase = 0
	Phase_PHASE_PREPARE         Phase = 1
	Phase_PHASE_INITIAL_CLUSTER Phase = 2
	Phase_PHASE_JOIN_EXISTING   Phase = 3
	// Cancel a previous prepare (it times out eventually)
	Phase_PHASE_CANCEL_PREPARE Phase = 4
)

// Enum value maps for Phase.
var (
	Phase_name = map[int32]string{
		0: "PHASE_UNKNOWN",
		1: "PHASE_PREPARE",
		2: "PHASE_INITIAL_CLUSTER",
		3: "PHASE_JOIN_EXISTING",
		4: "PHASE_CANCEL_PREPARE",
	}
	Phase_value = map[string]int32{
		"PHASE_UNKNOWN":         0,
		"PHASE_PREPARE":         1,
		"PHASE_INITIAL_CLUSTER": 2,
		"PHASE_JOIN_EXISTING":   3,
		"PHASE_CANCEL_PREPARE":  4,
	}
)

func (x Phase) Enum() *Phase {
	p := new(Phase)
	*p = x
	return p
}

func (x Phase) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (Phase) Descriptor() protoreflect.EnumDescriptor {
	return file_pkg_apis_etcd_etcdapi_proto_enumTypes[0].Descriptor()
}

func (Phase) Type() protoreflect.EnumType {
	return &file_pkg_apis_etcd_etcdapi_proto_enumTypes[0]
}

func (x Phase) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use Phase.Descriptor instead.
func (Phase) EnumDescriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{0}
}

type ClusterSpec struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberCount   int32                  `protobuf:"varint,1,opt,name=member_count,json=memberCount,proto3" json:"member_count,omitempty"`
	EtcdVersion   string                 `protobuf:"bytes,2,opt,name=etcd_version,json=etcdVersion,proto3" json:"etcd_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ClusterSpec) Reset() {
	*x = ClusterSpec{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ClusterSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ClusterSpec) ProtoMessage() {}

func (x *ClusterSpec) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ClusterSpec.ProtoReflect.Descriptor instead.
func (*ClusterSpec) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{0}
}

func (x *ClusterSpec) GetMemberCount() int32 {
	if x != nil {
		return x.MemberCount
	}
	return 0
}

func (x *ClusterSpec) GetEtcdVersion() string {
	if x != nil {
		return x.EtcdVersion
	}
	return ""
}

type Command struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	Timestamp int64                  `protobuf:"varint,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	// If restore backup is set, this indicates a request to restore the specified backup
	// This is not normally safe (potential for data loss if the backup is out of date),
	// but either the administrator can set this in a DR scenario,
	// or we set it ourselves immediately after having performed a quarantined backup
	RestoreBackup *RestoreBackupCommand `protobuf:"bytes,10,opt,name=restore_backup,json=restoreBackup,proto3" json:"restore_backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Command) Reset() {
	*x = Command{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Command) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Command) ProtoMessage() {}

func (x *Command) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Command.ProtoReflect.Descriptor instead.
func (*Command) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{1}
}

func (x *Command) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *Command) GetRestoreBackup() *RestoreBackupCommand {
	if x != nil {
		return x.RestoreBackup
	}
	return nil
}

type RestoreBackupCommand struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// The new cluster spec we should restore into
	ClusterSpec   *ClusterSpec `protobuf:"bytes,1,opt,name=cluster_spec,json=clusterSpec,proto3" json:"cluster_spec,omitempty"`
	Backup        string       `protobuf:"bytes,3,opt,name=backup,proto3" json:"backup,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RestoreBackupCommand) Reset() {
	*x = RestoreBackupCommand{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RestoreBackupCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RestoreBackupCommand) ProtoMessage() {}

func (x *RestoreBackupCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RestoreBackupCommand.ProtoReflect.Descriptor instead.
func (*RestoreBackupCommand) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{2}
}

func (x *RestoreBackupCommand) GetClusterSpec() *ClusterSpec {
	if x != nil {
		return x.ClusterSpec
	}
	return nil
}

func (x *RestoreBackupCommand) GetBackup() string {
	if x != nil {
		return x.Backup
	}
	return ""
}

type CreateNewClusterCommand struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ClusterSpec   *ClusterSpec           `protobuf:"bytes,1,opt,name=cluster_spec,json=clusterSpec,proto3" json:"cluster_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateNewClusterCommand) Reset() {
	*x = CreateNewClusterCommand{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateNewClusterCommand) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateNewClusterCommand) ProtoMessage() {}

func (x *CreateNewClusterCommand) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateNewClusterCommand.ProtoReflect.Descriptor instead.
func (*CreateNewClusterCommand) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{3}
}

func (x *CreateNewClusterCommand) GetClusterSpec() *ClusterSpec {
	if x != nil {
		return x.ClusterSpec
	}
	return nil
}

type GetInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetInfoRequest) Reset() {
	*x = GetInfoRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoRequest) ProtoMessage() {}

func (x *GetInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoRequest.ProtoReflect.Descriptor instead.
func (*GetInfoRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{4}
}

type GetInfoResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ClusterName       string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	NodeConfiguration *EtcdNode              `protobuf:"bytes,5,opt,name=node_configuration,json=nodeConfiguration,proto3" json:"node_configuration,omitempty"`
	EtcdState         *EtcdState             `protobuf:"bytes,6,opt,name=etcd_state,json=etcdState,proto3" json:"etcd_state,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetInfoResponse) Reset() {
	*x = GetInfoResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetInfoResponse) ProtoMessage() {}

func (x *GetInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetInfoResponse.ProtoReflect.Descriptor instead.
func (*GetInfoResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{5}
}

func (x *GetInfoResponse) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

func (x *GetInfoResponse) GetNodeConfiguration() *EtcdNode {
	if x != nil {
		return x.NodeConfiguration
	}
	return nil
}

func (x *GetInfoResponse) GetEtcdState() *EtcdState {
	if x != nil {
		return x.EtcdState
	}
	return nil
}

type UpdateEndpointsRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Contains information about the current nodes
	// It can be used for nodes to update /etc/hosts
	MemberMap     *MemberMap `protobuf:"bytes,1,opt,name=member_map,json=memberMap,proto3" json:"member_map,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEndpointsRequest) Reset() {
	*x = UpdateEndpointsRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointsRequest) ProtoMessage() {}

func (x *UpdateEndpointsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointsRequest.ProtoReflect.Descriptor instead.
func (*UpdateEndpointsRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateEndpointsRequest) GetMemberMap() *MemberMap {
	if x != nil {
		return x.MemberMap
	}
	return nil
}

type MemberMap struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Members       []*MemberMapInfo       `protobuf:"bytes,1,rep,name=members,proto3" json:"members,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberMap) Reset() {
	*x = MemberMap{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMap) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMap) ProtoMessage() {}

func (x *MemberMap) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMap.ProtoReflect.Descriptor instead.
func (*MemberMap) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{7}
}

func (x *MemberMap) GetMembers() []*MemberMapInfo {
	if x != nil {
		return x.Members
	}
	return nil
}

type MemberMapInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Dns           string                 `protobuf:"bytes,2,opt,name=dns,proto3" json:"dns,omitempty"`
	Addresses     []string               `protobuf:"bytes,3,rep,name=addresses,proto3" json:"addresses,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MemberMapInfo) Reset() {
	*x = MemberMapInfo{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MemberMapInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MemberMapInfo) ProtoMessage() {}

func (x *MemberMapInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MemberMapInfo.ProtoReflect.Descriptor instead.
func (*MemberMapInfo) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{8}
}

func (x *MemberMapInfo) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *MemberMapInfo) GetDns() string {
	if x != nil {
		return x.Dns
	}
	return ""
}

func (x *MemberMapInfo) GetAddresses() []string {
	if x != nil {
		return x.Addresses
	}
	return nil
}

type UpdateEndpointsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateEndpointsResponse) Reset() {
	*x = UpdateEndpointsResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateEndpointsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateEndpointsResponse) ProtoMessage() {}

func (x *UpdateEndpointsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateEndpointsResponse.ProtoReflect.Descriptor instead.
func (*UpdateEndpointsResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{9}
}

type BackupInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	EtcdVersion   string                 `protobuf:"bytes,1,opt,name=etcd_version,json=etcdVersion,proto3" json:"etcd_version,omitempty"`
	Timestamp     int64                  `protobuf:"varint,2,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	ClusterSpec   *ClusterSpec           `protobuf:"bytes,3,opt,name=cluster_spec,json=clusterSpec,proto3" json:"cluster_spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackupInfo) Reset() {
	*x = BackupInfo{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackupInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackupInfo) ProtoMessage() {}

func (x *BackupInfo) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackupInfo.ProtoReflect.Descriptor instead.
func (*BackupInfo) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{10}
}

func (x *BackupInfo) GetEtcdVersion() string {
	if x != nil {
		return x.EtcdVersion
	}
	return ""
}

func (x *BackupInfo) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

func (x *BackupInfo) GetClusterSpec() *ClusterSpec {
	if x != nil {
		return x.ClusterSpec
	}
	return nil
}

type CommonRequestHeader struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	LeadershipToken string                 `protobuf:"bytes,1,opt,name=leadership_token,json=leadershipToken,proto3" json:"leadership_token,omitempty"`
	ClusterName     string                 `protobuf:"bytes,2,opt,name=cluster_name,json=clusterName,proto3" json:"cluster_name,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CommonRequestHeader) Reset() {
	*x = CommonRequestHeader{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CommonRequestHeader) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CommonRequestHeader) ProtoMessage() {}

func (x *CommonRequestHeader) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CommonRequestHeader.ProtoReflect.Descriptor instead.
func (*CommonRequestHeader) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{11}
}

func (x *CommonRequestHeader) GetLeadershipToken() string {
	if x != nil {
		return x.LeadershipToken
	}
	return ""
}

func (x *CommonRequestHeader) GetClusterName() string {
	if x != nil {
		return x.ClusterName
	}
	return ""
}

type DoBackupRequest struct {
	state   protoimpl.MessageState `protogen:"open.v1"`
	Header  *CommonRequestHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Storage string                 `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	// If allow_offline_backup is true, backup will be permitted even if etcd is not running on the node
	AllowOfflineBackup bool        `protobuf:"varint,4,opt,name=allow_offline_backup,json=allowOfflineBackup,proto3" json:"allow_offline_backup,omitempty"`
	Info               *BackupInfo `protobuf:"bytes,10,opt,name=info,proto3" json:"info,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *DoBackupRequest) Reset() {
	*x = DoBackupRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoBackupRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoBackupRequest) ProtoMessage() {}

func (x *DoBackupRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoBackupRequest.ProtoReflect.Descriptor instead.
func (*DoBackupRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{12}
}

func (x *DoBackupRequest) GetHeader() *CommonRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DoBackupRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *DoBackupRequest) GetAllowOfflineBackup() bool {
	if x != nil {
		return x.AllowOfflineBackup
	}
	return false
}

func (x *DoBackupRequest) GetInfo() *BackupInfo {
	if x != nil {
		return x.Info
	}
	return nil
}

type DoBackupResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoBackupResponse) Reset() {
	*x = DoBackupResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoBackupResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoBackupResponse) ProtoMessage() {}

func (x *DoBackupResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoBackupResponse.ProtoReflect.Descriptor instead.
func (*DoBackupResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{13}
}

func (x *DoBackupResponse) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type DoRestoreRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CommonRequestHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Storage       string                 `protobuf:"bytes,2,opt,name=storage,proto3" json:"storage,omitempty"`
	BackupName    string                 `protobuf:"bytes,4,opt,name=backup_name,json=backupName,proto3" json:"backup_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRestoreRequest) Reset() {
	*x = DoRestoreRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRestoreRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRestoreRequest) ProtoMessage() {}

func (x *DoRestoreRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRestoreRequest.ProtoReflect.Descriptor instead.
func (*DoRestoreRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{14}
}

func (x *DoRestoreRequest) GetHeader() *CommonRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *DoRestoreRequest) GetStorage() string {
	if x != nil {
		return x.Storage
	}
	return ""
}

func (x *DoRestoreRequest) GetBackupName() string {
	if x != nil {
		return x.BackupName
	}
	return ""
}

type DoRestoreResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DoRestoreResponse) Reset() {
	*x = DoRestoreResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DoRestoreResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DoRestoreResponse) ProtoMessage() {}

func (x *DoRestoreResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DoRestoreResponse.ProtoReflect.Descriptor instead.
func (*DoRestoreResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{15}
}

type StopEtcdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CommonRequestHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEtcdRequest) Reset() {
	*x = StopEtcdRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEtcdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEtcdRequest) ProtoMessage() {}

func (x *StopEtcdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEtcdRequest.ProtoReflect.Descriptor instead.
func (*StopEtcdRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{16}
}

func (x *StopEtcdRequest) GetHeader() *CommonRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

type StopEtcdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StopEtcdResponse) Reset() {
	*x = StopEtcdResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StopEtcdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StopEtcdResponse) ProtoMessage() {}

func (x *StopEtcdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StopEtcdResponse.ProtoReflect.Descriptor instead.
func (*StopEtcdResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{17}
}

type JoinClusterRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Header        *CommonRequestHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	Phase         Phase                  `protobuf:"varint,2,opt,name=phase,proto3,enum=etcd.Phase" json:"phase,omitempty"`
	ClusterToken  string                 `protobuf:"bytes,4,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	Nodes         []*EtcdNode            `protobuf:"bytes,5,rep,name=nodes,proto3" json:"nodes,omitempty"`
	AddNode       *EtcdNode              `protobuf:"bytes,6,opt,name=add_node,json=addNode,proto3" json:"add_node,omitempty"`
	EtcdVersion   string                 `protobuf:"bytes,7,opt,name=etcd_version,json=etcdVersion,proto3" json:"etcd_version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterRequest) Reset() {
	*x = JoinClusterRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterRequest) ProtoMessage() {}

func (x *JoinClusterRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterRequest.ProtoReflect.Descriptor instead.
func (*JoinClusterRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{18}
}

func (x *JoinClusterRequest) GetHeader() *CommonRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *JoinClusterRequest) GetPhase() Phase {
	if x != nil {
		return x.Phase
	}
	return Phase_PHASE_UNKNOWN
}

func (x *JoinClusterRequest) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *JoinClusterRequest) GetNodes() []*EtcdNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

func (x *JoinClusterRequest) GetAddNode() *EtcdNode {
	if x != nil {
		return x.AddNode
	}
	return nil
}

func (x *JoinClusterRequest) GetEtcdVersion() string {
	if x != nil {
		return x.EtcdVersion
	}
	return ""
}

type JoinClusterResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *JoinClusterResponse) Reset() {
	*x = JoinClusterResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *JoinClusterResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*JoinClusterResponse) ProtoMessage() {}

func (x *JoinClusterResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use JoinClusterResponse.ProtoReflect.Descriptor instead.
func (*JoinClusterResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{19}
}

type ReconfigureRequest struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Header         *CommonRequestHeader   `protobuf:"bytes,1,opt,name=header,proto3" json:"header,omitempty"`
	SetEtcdVersion string                 `protobuf:"bytes,10,opt,name=set_etcd_version,json=setEtcdVersion,proto3" json:"set_etcd_version,omitempty"`
	// Note that because this is bool this must always be specified
	Quarantined bool `protobuf:"varint,11,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	// Note that because this is bool we need two fields
	EnableTls     bool `protobuf:"varint,12,opt,name=enable_tls,json=enableTls,proto3" json:"enable_tls,omitempty"` //bool disable_tls = 13;
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconfigureRequest) Reset() {
	*x = ReconfigureRequest{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconfigureRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconfigureRequest) ProtoMessage() {}

func (x *ReconfigureRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconfigureRequest.ProtoReflect.Descriptor instead.
func (*ReconfigureRequest) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{20}
}

func (x *ReconfigureRequest) GetHeader() *CommonRequestHeader {
	if x != nil {
		return x.Header
	}
	return nil
}

func (x *ReconfigureRequest) GetSetEtcdVersion() string {
	if x != nil {
		return x.SetEtcdVersion
	}
	return ""
}

func (x *ReconfigureRequest) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

func (x *ReconfigureRequest) GetEnableTls() bool {
	if x != nil {
		return x.EnableTls
	}
	return false
}

type ReconfigureResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReconfigureResponse) Reset() {
	*x = ReconfigureResponse{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReconfigureResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReconfigureResponse) ProtoMessage() {}

func (x *ReconfigureResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReconfigureResponse.ProtoReflect.Descriptor instead.
func (*ReconfigureResponse) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{21}
}

type EtcdCluster struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	DesiredClusterSize int32                  `protobuf:"varint,1,opt,name=desired_cluster_size,json=desiredClusterSize,proto3" json:"desired_cluster_size,omitempty"`
	// int32 peer_port = 2;
	// int32 client_port = 3;
	// string cluster_name = 4;
	ClusterToken string `protobuf:"bytes,5,opt,name=cluster_token,json=clusterToken,proto3" json:"cluster_token,omitempty"`
	// string my_id = 6;
	Nodes         []*EtcdNode `protobuf:"bytes,7,rep,name=nodes,proto3" json:"nodes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdCluster) Reset() {
	*x = EtcdCluster{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdCluster) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdCluster) ProtoMessage() {}

func (x *EtcdCluster) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdCluster.ProtoReflect.Descriptor instead.
func (*EtcdCluster) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{22}
}

func (x *EtcdCluster) GetDesiredClusterSize() int32 {
	if x != nil {
		return x.DesiredClusterSize
	}
	return 0
}

func (x *EtcdCluster) GetClusterToken() string {
	if x != nil {
		return x.ClusterToken
	}
	return ""
}

func (x *EtcdCluster) GetNodes() []*EtcdNode {
	if x != nil {
		return x.Nodes
	}
	return nil
}

type EtcdNode struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Name                  string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	PeerUrls              []string               `protobuf:"bytes,2,rep,name=peer_urls,json=peerUrls,proto3" json:"peer_urls,omitempty"`
	ClientUrls            []string               `protobuf:"bytes,3,rep,name=client_urls,json=clientUrls,proto3" json:"client_urls,omitempty"`
	QuarantinedClientUrls []string               `protobuf:"bytes,4,rep,name=quarantined_client_urls,json=quarantinedClientUrls,proto3" json:"quarantined_client_urls,omitempty"`
	TlsEnabled            bool                   `protobuf:"varint,5,opt,name=tls_enabled,json=tlsEnabled,proto3" json:"tls_enabled,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *EtcdNode) Reset() {
	*x = EtcdNode{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdNode) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdNode) ProtoMessage() {}

func (x *EtcdNode) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdNode.ProtoReflect.Descriptor instead.
func (*EtcdNode) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{23}
}

func (x *EtcdNode) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *EtcdNode) GetPeerUrls() []string {
	if x != nil {
		return x.PeerUrls
	}
	return nil
}

func (x *EtcdNode) GetClientUrls() []string {
	if x != nil {
		return x.ClientUrls
	}
	return nil
}

func (x *EtcdNode) GetQuarantinedClientUrls() []string {
	if x != nil {
		return x.QuarantinedClientUrls
	}
	return nil
}

func (x *EtcdNode) GetTlsEnabled() bool {
	if x != nil {
		return x.TlsEnabled
	}
	return false
}

type EtcdState struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NewCluster    bool                   `protobuf:"varint,1,opt,name=new_cluster,json=newCluster,proto3" json:"new_cluster,omitempty"`
	Cluster       *EtcdCluster           `protobuf:"bytes,2,opt,name=cluster,proto3" json:"cluster,omitempty"`
	EtcdVersion   string                 `protobuf:"bytes,3,opt,name=etcd_version,json=etcdVersion,proto3" json:"etcd_version,omitempty"`
	Quarantined   bool                   `protobuf:"varint,4,opt,name=quarantined,proto3" json:"quarantined,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EtcdState) Reset() {
	*x = EtcdState{}
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EtcdState) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EtcdState) ProtoMessage() {}

func (x *EtcdState) ProtoReflect() protoreflect.Message {
	mi := &file_pkg_apis_etcd_etcdapi_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EtcdState.ProtoReflect.Descriptor instead.
func (*EtcdState) Descriptor() ([]byte, []int) {
	return file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP(), []int{24}
}

func (x *EtcdState) GetNewCluster() bool {
	if x != nil {
		return x.NewCluster
	}
	return false
}

func (x *EtcdState) GetCluster() *EtcdCluster {
	if x != nil {
		return x.Cluster
	}
	return nil
}

func (x *EtcdState) GetEtcdVersion() string {
	if x != nil {
		return x.EtcdVersion
	}
	return ""
}

func (x *EtcdState) GetQuarantined() bool {
	if x != nil {
		return x.Quarantined
	}
	return false
}

var File_pkg_apis_etcd_etcdapi_proto protoreflect.FileDescriptor

const file_pkg_apis_etcd_etcdapi_proto_rawDesc = "" +
	"\n" +
	"\x1bpkg/apis/etcd/etcdapi.proto\x12\x04etcd\"S\n" +
	"\vClusterSpec\x12!\n" +
	"\fmember_count\x18\x01 \x01(\x05R\vmemberCount\x12!\n" +
	"\fetcd_version\x18\x02 \x01(\tR\vetcdVersion\"j\n" +
	"\aCommand\x12\x1c\n" +
	"\ttimestamp\x18\x01 \x01(\x03R\ttimestamp\x12A\n" +
	"\x0erestore_backup\x18\n" +
	" \x01(\v2\x1a.etcd.RestoreBackupCommandR\rrestoreBackup\"d\n" +
	"\x14RestoreBackupCommand\x124\n" +
	"\fcluster_spec\x18\x01 \x01(\v2\x11.etcd.ClusterSpecR\vclusterSpec\x12\x16\n" +
	"\x06backup\x18\x03 \x01(\tR\x06backup\"O\n" +
	"\x17CreateNewClusterCommand\x124\n" +
	"\fcluster_spec\x18\x01 \x01(\v2\x11.etcd.ClusterSpecR\vclusterSpec\"\x10\n" +
	"\x0eGetInfoRequest\"\xa3\x01\n" +
	"\x0fGetInfoResponse\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\x12=\n" +
	"\x12node_configuration\x18\x05 \x01(\v2\x0e.etcd.EtcdNodeR\x11nodeConfiguration\x12.\n" +
	"\n" +
	"etcd_state\x18\x06 \x01(\v2\x0f.etcd.EtcdStateR\tetcdState\"H\n" +
	"\x16UpdateEndpointsRequest\x12.\n" +
	"\n" +
	"member_map\x18\x01 \x01(\v2\x0f.etcd.MemberMapR\tmemberMap\":\n" +
	"\tMemberMap\x12-\n" +
	"\amembers\x18\x01 \x03(\v2\x13.etcd.MemberMapInfoR\amembers\"S\n" +
	"\rMemberMapInfo\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x10\n" +
	"\x03dns\x18\x02 \x01(\tR\x03dns\x12\x1c\n" +
	"\taddresses\x18\x03 \x03(\tR\taddresses\"\x19\n" +
	"\x17UpdateEndpointsResponse\"\x83\x01\n" +
	"\n" +
	"BackupInfo\x12!\n" +
	"\fetcd_version\x18\x01 \x01(\tR\vetcdVersion\x12\x1c\n" +
	"\ttimestamp\x18\x02 \x01(\x03R\ttimestamp\x124\n" +
	"\fcluster_spec\x18\x03 \x01(\v2\x11.etcd.ClusterSpecR\vclusterSpec\"c\n" +
	"\x13CommonRequestHeader\x12)\n" +
	"\x10leadership_token\x18\x01 \x01(\tR\x0fleadershipToken\x12!\n" +
	"\fcluster_name\x18\x02 \x01(\tR\vclusterName\"\xb6\x01\n" +
	"\x0fDoBackupRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.etcd.CommonRequestHeaderR\x06header\x12\x18\n" +
	"\astorage\x18\x02 \x01(\tR\astorage\x120\n" +
	"\x14allow_offline_backup\x18\x04 \x01(\bR\x12allowOfflineBackup\x12$\n" +
	"\x04info\x18\n" +
	" \x01(\v2\x10.etcd.BackupInfoR\x04info\"&\n" +
	"\x10DoBackupResponse\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\x80\x01\n" +
	"\x10DoRestoreRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.etcd.CommonRequestHeaderR\x06header\x12\x18\n" +
	"\astorage\x18\x02 \x01(\tR\astorage\x12\x1f\n" +
	"\vbackup_name\x18\x04 \x01(\tR\n" +
	"backupName\"\x13\n" +
	"\x11DoRestoreResponse\"D\n" +
	"\x0fStopEtcdRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.etcd.CommonRequestHeaderR\x06header\"\x12\n" +
	"\x10StopEtcdResponse\"\x83\x02\n" +
	"\x12JoinClusterRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.etcd.CommonRequestHeaderR\x06header\x12!\n" +
	"\x05phase\x18\x02 \x01(\x0e2\v.etcd.PhaseR\x05phase\x12#\n" +
	"\rcluster_token\x18\x04 \x01(\tR\fclusterToken\x12$\n" +
	"\x05nodes\x18\x05 \x03(\v2\x0e.etcd.EtcdNodeR\x05nodes\x12)\n" +
	"\badd_node\x18\x06 \x01(\v2\x0e.etcd.EtcdNodeR\aaddNode\x12!\n" +
	"\fetcd_version\x18\a \x01(\tR\vetcdVersion\"\x15\n" +
	"\x13JoinClusterResponse\"\xb2\x01\n" +
	"\x12ReconfigureRequest\x121\n" +
	"\x06header\x18\x01 \x01(\v2\x19.etcd.CommonRequestHeaderR\x06header\x12(\n" +
	"\x10set_etcd_version\x18\n" +
	" \x01(\tR\x0esetEtcdVersion\x12 \n" +
	"\vquarantined\x18\v \x01(\bR\vquarantined\x12\x1d\n" +
	"\n" +
	"enable_tls\x18\f \x01(\bR\tenableTls\"\x15\n" +
	"\x13ReconfigureResponse\"\x8a\x01\n" +
	"\vEtcdCluster\x120\n" +
	"\x14desired_cluster_size\x18\x01 \x01(\x05R\x12desiredClusterSize\x12#\n" +
	"\rcluster_token\x18\x05 \x01(\tR\fclusterToken\x12$\n" +
	"\x05nodes\x18\a \x03(\v2\x0e.etcd.EtcdNodeR\x05nodes\"\xb5\x01\n" +
	"\bEtcdNode\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12\x1b\n" +
	"\tpeer_urls\x18\x02 \x03(\tR\bpeerUrls\x12\x1f\n" +
	"\vclient_urls\x18\x03 \x03(\tR\n" +
	"clientUrls\x126\n" +
	"\x17quarantined_client_urls\x18\x04 \x03(\tR\x15quarantinedClientUrls\x12\x1f\n" +
	"\vtls_enabled\x18\x05 \x01(\bR\n" +
	"tlsEnabled\"\x9e\x01\n" +
	"\tEtcdState\x12\x1f\n" +
	"\vnew_cluster\x18\x01 \x01(\bR\n" +
	"newCluster\x12+\n" +
	"\acluster\x18\x02 \x01(\v2\x11.etcd.EtcdClusterR\acluster\x12!\n" +
	"\fetcd_version\x18\x03 \x01(\tR\vetcdVersion\x12 \n" +
	"\vquarantined\x18\x04 \x01(\bR\vquarantined*{\n" +
	"\x05Phase\x12\x11\n" +
	"\rPHASE_UNKNOWN\x10\x00\x12\x11\n" +
	"\rPHASE_PREPARE\x10\x01\x12\x19\n" +
	"\x15PHASE_INITIAL_CLUSTER\x10\x02\x12\x17\n" +
	"\x13PHASE_JOIN_EXISTING\x10\x03\x12\x18\n" +
	"\x14PHASE_CANCEL_PREPARE\x10\x042\xd8\x03\n" +
	"\x12EtcdManagerService\x126\n" +
	"\aGetInfo\x12\x14.etcd.GetInfoRequest\x1a\x15.etcd.GetInfoResponse\x12N\n" +
	"\x0fUpdateEndpoints\x12\x1c.etcd.UpdateEndpointsRequest\x1a\x1d.etcd.UpdateEndpointsResponse\x12B\n" +
	"\vJoinCluster\x12\x18.etcd.JoinClusterRequest\x1a\x19.etcd.JoinClusterResponse\x12B\n" +
	"\vReconfigure\x12\x18.etcd.ReconfigureRequest\x1a\x19.etcd.ReconfigureResponse\x129\n" +
	"\bDoBackup\x12\x15.etcd.DoBackupRequest\x1a\x16.etcd.DoBackupResponse\x12<\n" +
	"\tDoRestore\x12\x16.etcd.DoRestoreRequest\x1a\x17.etcd.DoRestoreResponse\x129\n" +
	"\bStopEtcd\x12\x15.etcd.StopEtcdRequest\x1a\x16.etcd.StopEtcdResponseB(Z&sigs.k8s.io/etcd-manager/pkg/apis/etcdb\x06proto3"

var (
	file_pkg_apis_etcd_etcdapi_proto_rawDescOnce sync.Once
	file_pkg_apis_etcd_etcdapi_proto_rawDescData []byte
)

func file_pkg_apis_etcd_etcdapi_proto_rawDescGZIP() []byte {
	file_pkg_apis_etcd_etcdapi_proto_rawDescOnce.Do(func() {
		file_pkg_apis_etcd_etcdapi_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pkg_apis_etcd_etcdapi_proto_rawDesc), len(file_pkg_apis_etcd_etcdapi_proto_rawDesc)))
	})
	return file_pkg_apis_etcd_etcdapi_proto_rawDescData
}

var file_pkg_apis_etcd_etcdapi_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_pkg_apis_etcd_etcdapi_proto_msgTypes = make([]protoimpl.MessageInfo, 25)
var file_pkg_apis_etcd_etcdapi_proto_goTypes = []any{
	(Phase)(0),                      // 0: etcd.Phase
	(*ClusterSpec)(nil),             // 1: etcd.ClusterSpec
	(*Command)(nil),                 // 2: etcd.Command
	(*RestoreBackupCommand)(nil),    // 3: etcd.RestoreBackupCommand
	(*CreateNewClusterCommand)(nil), // 4: etcd.CreateNewClusterCommand
	(*GetInfoRequest)(nil),          // 5: etcd.GetInfoRequest
	(*GetInfoResponse)(nil),         // 6: etcd.GetInfoResponse
	(*UpdateEndpointsRequest)(nil),  // 7: etcd.UpdateEndpointsRequest
	(*MemberMap)(nil),               // 8: etcd.MemberMap
	(*MemberMapInfo)(nil),           // 9: etcd.MemberMapInfo
	(*UpdateEndpointsResponse)(nil), // 10: etcd.UpdateEndpointsResponse
	(*BackupInfo)(nil),              // 11: etcd.BackupInfo
	(*CommonRequestHeader)(nil),     // 12: etcd.CommonRequestHeader
	(*DoBackupRequest)(nil),         // 13: etcd.DoBackupRequest
	(*DoBackupResponse)(nil),        // 14: etcd.DoBackupResponse
	(*DoRestoreRequest)(nil),        // 15: etcd.DoRestoreRequest
	(*DoRestoreResponse)(nil),       // 16: etcd.DoRestoreResponse
	(*StopEtcdRequest)(nil),         // 17: etcd.StopEtcdRequest
	(*StopEtcdResponse)(nil),        // 18: etcd.StopEtcdResponse
	(*JoinClusterRequest)(nil),      // 19: etcd.JoinClusterRequest
	(*JoinClusterResponse)(nil),     // 20: etcd.JoinClusterResponse
	(*ReconfigureRequest)(nil),      // 21: etcd.ReconfigureRequest
	(*ReconfigureResponse)(nil),     // 22: etcd.ReconfigureResponse
	(*EtcdCluster)(nil),             // 23: etcd.EtcdCluster
	(*EtcdNode)(nil),                // 24: etcd.EtcdNode
	(*EtcdState)(nil),               // 25: etcd.EtcdState
}
var file_pkg_apis_etcd_etcdapi_proto_depIdxs = []int32{
	3,  // 0: etcd.Command.restore_backup:type_name -> etcd.RestoreBackupCommand
	1,  // 1: etcd.RestoreBackupCommand.cluster_spec:type_name -> etcd.ClusterSpec
	1,  // 2: etcd.CreateNewClusterCommand.cluster_spec:type_name -> etcd.ClusterSpec
	24, // 3: etcd.GetInfoResponse.node_configuration:type_name -> etcd.EtcdNode
	25, // 4: etcd.GetInfoResponse.etcd_state:type_name -> etcd.EtcdState
	8,  // 5: etcd.UpdateEndpointsRequest.member_map:type_name -> etcd.MemberMap
	9,  // 6: etcd.MemberMap.members:type_name -> etcd.MemberMapInfo
	1,  // 7: etcd.BackupInfo.cluster_spec:type_name -> etcd.ClusterSpec
	12, // 8: etcd.DoBackupRequest.header:type_name -> etcd.CommonRequestHeader
	11, // 9: etcd.DoBackupRequest.info:type_name -> etcd.BackupInfo
	12, // 10: etcd.DoRestoreRequest.header:type_name -> etcd.CommonRequestHeader
	12, // 11: etcd.StopEtcdRequest.header:type_name -> etcd.CommonRequestHeader
	12, // 12: etcd.JoinClusterRequest.header:type_name -> etcd.CommonRequestHeader
	0,  // 13: etcd.JoinClusterRequest.phase:type_name -> etcd.Phase
	24, // 14: etcd.JoinClusterRequest.nodes:type_name -> etcd.EtcdNode
	24, // 15: etcd.JoinClusterRequest.add_node:type_name -> etcd.EtcdNode
	12, // 16: etcd.ReconfigureRequest.header:type_name -> etcd.CommonRequestHeader
	24, // 17: etcd.EtcdCluster.nodes:type_name -> etcd.EtcdNode
	23, // 18: etcd.EtcdState.cluster:type_name -> etcd.EtcdCluster
	5,  // 19: etcd.EtcdManagerService.GetInfo:input_type -> etcd.GetInfoRequest
	7,  // 20: etcd.EtcdManagerService.UpdateEndpoints:input_type -> etcd.UpdateEndpointsRequest
	19, // 21: etcd.EtcdManagerService.JoinCluster:input_type -> etcd.JoinClusterRequest
	21, // 22: etcd.EtcdManagerService.Reconfigure:input_type -> etcd.ReconfigureRequest
	13, // 23: etcd.EtcdManagerService.DoBackup:input_type -> etcd.DoBackupRequest
	15, // 24: etcd.EtcdManagerService.DoRestore:input_type -> etcd.DoRestoreRequest
	17, // 25: etcd.EtcdManagerService.StopEtcd:input_type -> etcd.StopEtcdRequest
	6,  // 26: etcd.EtcdManagerService.GetInfo:output_type -> etcd.GetInfoResponse
	10, // 27: etcd.EtcdManagerService.UpdateEndpoints:output_type -> etcd.UpdateEndpointsResponse
	20, // 28: etcd.EtcdManagerService.JoinCluster:output_type -> etcd.JoinClusterResponse
	22, // 29: etcd.EtcdManagerService.Reconfigure:output_type -> etcd.ReconfigureResponse
	14, // 30: etcd.EtcdManagerService.DoBackup:output_type -> etcd.DoBackupResponse
	16, // 31: etcd.EtcdManagerService.DoRestore:output_type -> etcd.DoRestoreResponse
	18, // 32: etcd.EtcdManagerService.StopEtcd:output_type -> etcd.StopEtcdResponse
	26, // [26:33] is the sub-list for method output_type
	19, // [19:26] is the sub-list for method input_type
	19, // [19:19] is the sub-list for extension type_name
	19, // [19:19] is the sub-list for extension extendee
	0,  // [0:19] is the sub-list for field type_name
}

func init() { file_pkg_apis_etcd_etcdapi_proto_init() }
func file_pkg_apis_etcd_etcdapi_proto_init() {
	if File_pkg_apis_etcd_etcdapi_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pkg_apis_etcd_etcdapi_proto_rawDesc), len(file_pkg_apis_etcd_etcdapi_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   25,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pkg_apis_etcd_etcdapi_proto_goTypes,
		DependencyIndexes: file_pkg_apis_etcd_etcdapi_proto_depIdxs,
		EnumInfos:         file_pkg_apis_etcd_etcdapi_proto_enumTypes,
		MessageInfos:      file_pkg_apis_etcd_etcdapi_proto_msgTypes,
	}.Build()
	File_pkg_apis_etcd_etcdapi_proto = out.File
	file_pkg_apis_etcd_etcdapi_proto_goTypes = nil
	file_pkg_apis_etcd_etcdapi_proto_depIdxs = nil
}
