/*
Copyright 2022 The Kubernetes Authors.

Licensed under the Apache License, Version 2.0 (the "License");
you may not use this file except in compliance with the License.
You may obtain a copy of the License at

    http://www.apache.org/licenses/LICENSE-2.0

Unless required by applicable law or agreed to in writing, software
distributed under the License is distributed on an "AS IS" BASIS,
WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
See the License for the specific language governing permissions and
limitations under the License.
*/

package main

import (
	"fmt"
	"net"
	"os"
	"path/filepath"
	"reflect"
	"testing"
)

func getTestData(networkCIDR string, volumeProviderID string) *EtcdManagerOptions {
	var o EtcdManagerOptions
	o.InitDefaults()

	o.ClusterName = "test"
	o.BackupStorePath = "s3://test"

	o.NetworkCIDR = networkCIDR
	o.VolumeProviderID = volumeProviderID

	return &o
}

func assertTestResults(t *testing.T, err error, expected any, actual any) {
	if err != nil {
		t.Fatalf("unexpected error: %s", err)
	}

	if !reflect.DeepEqual(expected, actual) {
		t.Fatalf("expected '%+v', but got '%+v'", expected, actual)
	}
}

func TestRunEtcdManagerReturnsNetworkCIDROnlySupportedWithOpenstack(t *testing.T) {
	expectedErr := fmt.Errorf("network-cidr is only supported with provider 'openstack'")
	o := getTestData("192.168.0.0/16", "aws")

	actualErr := RunEtcdManager(o)

	assertTestResults(t, nil, expectedErr, actualErr)
}

func TestRunEtcdManagerReturnsErrorOnInvalidCIDR(t *testing.T) {
	invalidCIDR := "192.168.0.0/123"
	expectedErr := fmt.Errorf("parsing network-cidr: %w", &net.ParseError{Type: "CIDR address", Text: invalidCIDR})
	o := getTestData(invalidCIDR, "openstack")

	actualErr := RunEtcdManager(o)

	assertTestResults(t, nil, expectedErr, actualErr)
}

func writeTempEnvFile(t *testing.T, content string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "env")
	if err := os.WriteFile(path, []byte(content), 0600); err != nil {
		t.Fatalf("writing temp env file: %v", err)
	}
	return path
}

func TestLoadEnvFileAppliesValues(t *testing.T) {
	content := `# Generated by kops nodeup. Do not edit.

SIMPLE=value
WITH_EQUALS=a=b=c
EMPTY=
`
	path := writeTempEnvFile(t, content)

	// Register the keys so the test framework restores prior state on cleanup.
	for _, k := range []string{"SIMPLE", "WITH_EQUALS", "EMPTY"} {
		t.Setenv(k, "sentinel")
	}

	if err := loadEnvFile(path); err != nil {
		t.Fatalf("unexpected error: %v", err)
	}

	want := map[string]string{
		"SIMPLE":      "value",
		"WITH_EQUALS": "a=b=c",
		"EMPTY":       "",
	}
	for key, expected := range want {
		got, ok := os.LookupEnv(key)
		if !ok {
			t.Errorf("env %q not set, want %q", key, expected)
			continue
		}
		if got != expected {
			t.Errorf("env %q = %q, want %q", key, got, expected)
		}
	}
}

func TestLoadEnvFileEmptyAndCommentsOnly(t *testing.T) {
	for name, content := range map[string]string{
		"empty file":     "",
		"comments only":  "# just a comment\n\n   \n",
		"trailing blank": "# header\n",
	} {
		t.Run(name, func(t *testing.T) {
			path := writeTempEnvFile(t, content)
			if err := loadEnvFile(path); err != nil {
				t.Fatalf("unexpected error: %v", err)
			}
		})
	}
}

func TestLoadEnvFileErrors(t *testing.T) {
	t.Run("missing file", func(t *testing.T) {
		path := filepath.Join(t.TempDir(), "does-not-exist")
		if err := loadEnvFile(path); err == nil {
			t.Fatal("expected error for missing file, got nil")
		}
	})

	t.Run("missing equals", func(t *testing.T) {
		path := writeTempEnvFile(t, "NOEQUALS\n")
		if err := loadEnvFile(path); err == nil {
			t.Fatal("expected error for line missing '=', got nil")
		}
	})

	t.Run("empty key", func(t *testing.T) {
		path := writeTempEnvFile(t, "=value\n")
		if err := loadEnvFile(path); err == nil {
			t.Fatal("expected error for empty key, got nil")
		}
	})

	t.Run("invalid key", func(t *testing.T) {
		path := writeTempEnvFile(t, "BAD KEY=value\n")
		if err := loadEnvFile(path); err == nil {
			t.Fatal("expected error for invalid key, got nil")
		}
	})
}

func TestValidEnvKey(t *testing.T) {
	valid := []string{"FOO", "_FOO", "S3_ACCESS_KEY_ID", "a", "A1", "_", "x9_y"}
	for _, k := range valid {
		if !validEnvKey(k) {
			t.Errorf("validEnvKey(%q) = false, want true", k)
		}
	}

	invalid := []string{"", "9FOO", "FOO BAR", "FOO-BAR", "FOO.BAR", "FOO=BAR", "föö", "FOO\t"}
	for _, k := range invalid {
		if validEnvKey(k) {
			t.Errorf("validEnvKey(%q) = true, want false", k)
		}
	}
}
