name: CI

on:
  - push
  - pull_request

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        fetch-tags: 'true'
    - name: Build etcd-manager-slim
      run: |
        make ko-dist

  test:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run tests
      run: |
        make test-short

  test-upgradedowngrade:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run upgradedowngrade tests
      run: |
        make test-upgradedowngrade

  test-backuprestore:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run backuprestore tests
      run: |
        make test-backuprestore

  test-integration:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Run integration tests
      run: |
        make test-integration
